### ISSUE TITLE
Microphone permission in google

### ISSUE THREAD

**Issue by cuvner** [ttseng/micropal#1]
HI, there's no errors in the console; however the microbial web app is failing to use the mic. Also when the model is uploaded it duplicates the classes multiple times. Shame its not working as its a great resource for kids

**Comment by ttseng** [comment]
Hi Cuvner.  I am seeing that the microphone works - you might want to try clicking on the microphone icon in the address bar to confirm that permission has been given to access the microphone.  Once you do that, you should be able to verify in the "hearing" section that the noise levels change when you speak.

<img width="355" alt="image" src="https://github.com/user-attachments/assets/734ac295-05e2-4d23-9014-69abb58db2aa">

**Comment by cuvner** [comment]
We are still having the same issue, Microphone is on, microbit is paired but there's no sound being recognised through your website? I can use teachable machine without issue.  There is an error in the console
Uncaught (in promise) TypeError: classifier.classify is not a function
    at modelReady (ml.js:62:16)
    at callcallback.js:35:9

![IMG_2146 2](https://github.com/user-attachments/assets/6884c087-cbb1-499a-ae71-d1004fc77764)
